name: "Sprint Task"
description: "Backlog item for current or upcoming sprint"
title: "[Sprint] <task summary>"
labels: ["sprint-0"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done and why?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List measurable criteria for completion.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
    validations:
      required: true
  - type: input
    id: dependencies
    attributes:
      label: Dependencies
      description: Linked issues/ADRs that must be completed first.
  - type: dropdown
    id: size
    attributes:
      label: Size
      options:
        - XS
        - S
        - M
        - L
        - XL

