name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ hashFiles('package.json', 'pnpm-workspace.yaml') != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['22.x']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Enable Corepack and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
      - name: Install dependencies
        run: pnpm -w install
      - name: Lint (if present)
        run: pnpm -w -r run -if-present lint || echo 'No lint scripts.'
      - name: Typecheck (if present)
        run: pnpm -w -r run -if-present typecheck || echo 'No typecheck scripts.'
      - name: Build (if present)
        run: pnpm -w -r run -if-present build || echo 'No build scripts.'
      - name: Test (if present)
        run: pnpm -w -r run -if-present test || echo 'No tests.'
