name: Secrets Guard
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if .env files are tracked (allow .env.example)
        run: |
          tracked=$(git ls-files | grep -E '(^|/)\.env($|\.)' | grep -vE '(^|/)\.env\.example$' || true)
          if [ -n "$tracked" ]; then
            echo "::error::.env* files must not be tracked:\n$tracked"; exit 1
          fi
