name: Secrets Guard
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if .env files are tracked
        run: |
          if git ls-files | grep -E '^(\.env|.*\.env(\.|$))' ; then
            echo "::error::.env* files must not be tracked."; exit 1
          fi

