name: Vercel Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  preview:
    if: ${{ secrets.VERCEL_TOKEN != '' }}
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - run: npm i -g vercel@latest
      - name: Pull env (preview)
        run: vercel pull --yes --environment=preview --token $VERCEL_TOKEN
      - name: Build
        run: vercel build --token $VERCEL_TOKEN
      - name: Deploy
        id: deploy
        run: |
          URL=$(vercel deploy --prebuilt --token $VERCEL_TOKEN)
          echo "url=$URL" >> $GITHUB_OUTPUT
      - name: Comment preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const url = "${{ steps.deploy.outputs.url }}";
            if (!url) return;
            const pr = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner, repo: context.repo.repo, issue_number: pr,
              body: `✅ Preview deployed: ${url}`
            });

